title: Deathburgh
description: A skirmish wargame by Highlands Miniatures
theme: just-the-docs

url: https://ovejocangrejo.github.io/Deathburgh/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
