title: Deathburgh 
description: a tabletop skirmish wargame by Hihglands Miniatures
theme: just-the-docs
color_schme: dark
search_enabled: true
lang: "en"
url: https://just-the-docs.github.io
baseurl: "/Deathburgh"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
- name "inicio"
  link "/"
- name "Guía"
  link: "/"
-name: "PDFs"
  link: "/"

footer_content: "@ 2025, Highlands Miniatures, all rights reserved"